package com.Alizone.Payment;

public enum PaymentEvent {
	
	 	ORDER_CREATED,
	    CONTRACT_ACCEPTED,
	    PAYMENT_REDIRECTED,
	    ORDER_CANCELLED,

	    PAYMENT_CALLBACK_RECEIVED,
	    PAYMENT_CALLBACK_VERIFIED,

	    PAYMENT_SUCCESS,
	    PAYMENT_FAILED,

	    AMOUNT_MISMATCH,
	    SIGNATURE_INVALID,
	    FRAUD_SUSPECT,
	    
	    REFUND_REQUESTED,
	    REFUND_SUCCESS,
	    
	    SIGNUP_CREATED,
	    KVKK_ACCEPTED

}
